########################
### GENTOO MAKE.CONF ###
########################

# Compile Flags
COMMON_FLAGS="-march=native -O3 -pipe -flto"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="-C target-cpu=native"

# Makeopts
MAKEOPTS="-j8 -l8"

# Portage Options
PORTAGE_IONICE_COMMAND="ionice -c 3 -p \${PID}"
PORTAGE_NICENESS=19

# Emerge Options
EMERGE_DEFAULT_OPTS="--ask-enter-invalid --autounmask --autounmask-write --with-bdeps=y --keep-going=y --complete-graph=y --tree --verbose --jobs=8 --load-average=8"

# Features
FEATURES="parallel-fetch parallel-install split-log candy news"

# Use Flags
USE="-systemd -wayland -gnome -cosmic -kde -emacs -xemacs -cups -wifi -dvd -debug pgo lto dbus opengl harfbuzz nvidia elogind bluetooth pipewire pulseaudio X"

# Allow Proprietory Garbage
ACCEPT_LICENSE="*"

# Directories
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# Nvidia
VIDEO_CARDS="nvidia"
INPUT_DEVICES="libinput synaptics"

# Grub And Language
GRUB_PLATFORMS="efi-64"
LC_MESSAGES=C.UTF-8
